"""Insert dictionary data

Revision ID: dd60c67ad3e5
Revises: 50eb2dc8f2cd
Create Date: 2022-08-12 13:41:50.690220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd60c67ad3e5"
down_revision = "50eb2dc8f2cd"
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.execute("""insert into seq_platform (`name`, `description`)
        values ('PacBio', 'Pacific Biosciences'),
        ('ONT', 'Oxford Nanopore Technologies'),
        ('Illumina', 'Illumina');""");

    op.execute("""insert into sub_product_attr (`attr_name`, `description`)
        values ('run_name', 'The name of the PacBio run according to LIMS'),
        ('well_label', 'PacBio well (or cell) label'),
        ('flowcell_id', 'ONT flowcell id as recorded by the instrument'),
        ('run_id', 'Run id as generated by the ONT instrument'),
        ('id_run', 'Run id in the NPG run tracking system'),
        ('position', 'Illumina flowcell position (lane)');""");

    op.execute("""insert into qc_type (`qc_type`, `description`)
        values ('library', 'Sample/library evaluation'),
        ('sequencing', 'Sequencing/instrument evaliation');""");

    op.execute("""insert into qc_state_dict (`state`, `outcome`)
        values ('Passed', 1),
        ('Failed, Instrument', 0),
        ('Failed, SMRT cell', 0),
        ('Failed', 0),
        ('Aborted', 0),
        ('Undecided', NULL),
        ('Claimed', NULL),
        ('On hold', NULL);""");


def downgrade() -> None:

    op.execute('delete from seq_platform;');
    op.execute('delete from sub_product_attr;');
    op.execute('delete from qc_type;');
    op.execute('delete from qc_state_dict;');
