-- Dictionaries

insert into seq_platform (`name`, `description`) values
  ('PacBio', 'Pacific Biosciences'),
  ('ONT', 'Oxford Nanopore Technologies'),
  ('Illumina', 'Illumina');

insert into sub_product_attr (`attr_name`, `description`)
  values ('run_name', 'The name of the PacBio run according to LIMS'),
  ('well_label', 'PacBio well (or cell) label'),
  ('flowcell_id', 'ONT flowcell id as recorded by the instrument'),
  ('run_id', 'Run id as generated by the ONT instrument'),
  ('id_run', 'Run id in the NPG run tracking system'),
  ('position', 'Illumina flowcell position (lane)');

insert into user (`username`) values ('user1'), ('user2');

insert into qc_type (`qc_type`, `description`) values
  ('library', 'Sample/library evaluation'),
  ('sequencing', 'Sequencing/instrument evaliation');

insert into qc_state_dict (`state`, `outcome`)
  values ('Passed', 1),
         ('Failed, Instrument', 0),
         ('Failed, SMRT cell', 0),
         ('Failed', 0),
         ('Aborted', 0),
         ('Undecided', NULL),
         ('Claimed', NULL),
         ('On hold', NULL);

