name: Lint

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, devel]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        run: |
          pipx install ruff

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Check with ruff
        run: |
          ruff check lang_qc

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Set up JS requirements
        run: npm install
        working-directory: ./frontend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./frontend
