name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: [master, devel]

jobs:
  test-packaging:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: "Run pip install"
        run: |
          pip install ".[test]"


  test:
    runs-on: ubuntu-latest

    services:
      mysql-mlwh:
        image: mysql:8.4
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_TCP_PORT: 3306
          MYSQL_USER: "test"
          MYSQL_PASSWORD: "test"
          MYSQL_DATABASE: "mlwarehouse"
      mysql-qcdb:
        image: mysql:8.4
        ports:
          - 3307:3307
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: yes
          MYSQL_TCP_PORT: 3307
          MYSQL_USER: "test"
          MYSQL_PASSWORD: "test"
          MYSQL_DATABASE: "langqc"

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Run pip install
        run: |
          pip install ".[test]"

      - name: Run pytest
        run: |
          pytest

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        working-directory: ./frontend
      - run: npm run test
        working-directory: ./frontend
